version: "3"

services:
  auth-service:
    image: hexnaught/jwt-auth-service
    container_name: authservice
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongodb
      - MONGO_DB_NAME=authservice
      - MONGO_USERNAME=
      - MONGO_PASSWORD=
      - MONGO_AUTH_SOURCE=
      - BCRYPT_COST_FACTOR=12 # AppMin/Default: 10, Max: 31, Prefer: 12+ (12=200ms Resp|+1 Cost = 2* Resp Time)
      - JWT_SECRET=
      - JWT_TTL=15
      - JWT_ISS=
      - JWT_AUD=
      - TLS_DOMAINS=
      - GIN_MODE=debug
      - DEBUG=
    depends_on:
        - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    #   - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongoexpress:
    image: mongo-express
    container_name: mongoex
    links:
      - "mongo:mongo"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
